number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €≥≤±"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
lang: 'cn_sim'
experiment_name: 'cn_sim_chem_new_2022_09_21'
train_data: 'all_data'
valid_data: 'all_data/val_all'
manualSeed: 1111
workers: 0
batch_size: 32 #32
num_iter: 600000
valInterval: 10000
saved_model: '' #'saved_models/ch_sim_chem/iter_300000.pth'
FT: False
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'out_chem_word5_b0_new-out_chem_word5_b1_new-out_chem_word5_b2_new-out_chem_word5_b3_new-out_ch_word5_b0_new-out_ch_word5_b1_new-out_ch_word5_b2_new-out_ch_word5_b3_new-out_ch_word5_b3_new_1' # this is dataset folder in train_data
batch_ratio: '0.071428571-0.071428571-0.071428571-0.09375-0.142857143-0.142857143-0.142857143-0.15625-0.1875'
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False